### ISSUE TITLE
Define a better way to install extra packages

### ISSUE THREAD

**Issue by nbigaouette** [nbigaouette/pycors#41]
Extra packages are installed too after a successful Python build (see PR #37).

This is quite opinionated and a better solution should be used instead.

Steps to solve this:
* [x] Ask users confirmation before installing packages (PR #44)
* [x] Provide a way to choose/edit list of install packages (PR #50)
* [ ] Re-run install process (issue #48, PR #52)
